# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ExecutorService.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x45xecutorService.proto\x12\x16\x64ynamiccalls.Inventory\"R\n\x0eProductRequest\x12\x11\n\tproductId\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05price\x18\x03 \x01(\x02\x12\x10\n\x08quantity\x18\x04 \x01(\x05\"%\n\x12\x41\x64\x64ProductResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2t\n\x10InventoryService\x12`\n\naddProduct\x12&.dynamiccalls.Inventory.ProductRequest\x1a*.dynamiccalls.Inventory.AddProductResponseB\x17P\x01\xaa\x02\x12\x44ynamicCallsClientb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ExecutorService_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'P\001\252\002\022DynamicCallsClient'
  _globals['_PRODUCTREQUEST']._serialized_start=49
  _globals['_PRODUCTREQUEST']._serialized_end=131
  _globals['_ADDPRODUCTRESPONSE']._serialized_start=133
  _globals['_ADDPRODUCTRESPONSE']._serialized_end=170
  _globals['_INVENTORYSERVICE']._serialized_start=172
  _globals['_INVENTORYSERVICE']._serialized_end=288
# @@protoc_insertion_point(module_scope)
